- src/index.html
The starter pack example no longer worked.
> Updated version of dependencies

- docs/build-pipeline.md
Updates docs regarding unminified build of .gdz.
> CHILDTEMP-1373_Update-starter-pack-with-unminified-gdz-info

- src/main.js
Disables tabbing for buttons, links and inputs for when settings modal is open. (Re-enables it when modal is closed).
> Tab Disabling

- src/main.js
Ensure the buttons are disabled and correctly aria-labelled when the settings screen is open. These fixes are to make IE11 happy.
> Ensures buttons are disabled when settings is open

- src/index.html
- src/main.js
> Cgprod 801 sign in

- src/account/account.js
Updates page-to-return-to string in the `gmi.account.authorise()` URL.
> CGPROD-957_Updates-authorise-method-in-starter-pack

- src/index.html
- src/main.js
Update send stats example and add setScreenStat example
> Update GMI stats examples for ATI system

- docs/gmi.md
- src/index.html
- src/main.js
Adds baseCounterName to example output and update docs for gmi.
> baseCounterName

- src/main.js
- src/style.css
Updated stats format.
Improvements to setStatsScreen example
> Updated stats format.

- src/main.js
- src/style.css
Adds authorise state into the mix
> Add Authorise state

- src/main.js
- src/style.css
Display responses using Promise resolver rather than setTimeout
> Cgprod 1292 auth

- docs/settings.md
- docs/stats.md
Amends docs (mainly formatting but a few minor amends to the stats stuff).
> CGPROD-1387_Stats-docs 

- docs/gmi.md
When fully implemented this should be replaced with full documentation
around the achievements system.
> Added note to docs about disbaled achievements

- .gitignore
- docs/working-with-gmi.md
- index.js
- package-lock.json
- package.json
- src/main.js
Use decodeAudioData to buffer audio samples instead of using built in
web audio api play method. This should be more representative of audio
format playback compatibility.
https://jira.dev.bbc.co.uk/browse/CGPROD-1501
> CGPROD-1501 Buffer audio playback test

- src/main.js
Code example now matches docs.
> Removed redundant toggle value

- docs/gmi.md
changes to Pick'n'mix GMI provide promise based sign-in returns.
> NOTICKET update GMI docs for Pick'n'mix GMI

- docs/testing-in-a-mobile-app.md
> CGPROD-1974 PTI docs

- src/achievements.js
This causes issues with automated testing.
> Remove set achievement on page load

- docs/achievements.md
Updates achievements documentation.
> CGPROD-2507_Achievements-Documentation-Update

- docs/game-delivery-definitions.md
> Update main readme

- src/main.js
-add unique DOM identifiers for targeting tests within Webcore
> add unique data-test-id attributes

- docs/build-pipeline.md
- package-lock.json
Update guidelines for sourcemaps
New version package lock
> Sourcemaps
